from typing import TypedDict, List, Optional, Annotated
import operator

class AgentState(TypedDict):
    """
    Represents the shared state of the multi-agent system.
    
    This TypedDict acts as the schema for the data passed between agents 
    in the LangGraph workflow, storing user inputs, agent instructions, 
    and the intermediate research reports generated by each node.
    """
    # User input and extracted metadata
    query: str
    tickers: List[str]
    investment_style: Optional[str]  # Target style, e.g., "growth", "value", "dividend"

    # Dynamic instructions for specialized agents
    data_analyst_instructions: Optional[str]
    news_analyst_instructions: Optional[str]
    trend_analyst_instructions: Optional[str]
    pattern_analyst_instructions: Optional[str]
    indicator_analyst_instructions: Optional[str]

    # Intermediate analysis results
    data_analysis: Optional[str]
    news_analysis: Optional[str]
    
    # Specialized technical analysis reports
    trend_analysis: Optional[str]
    pattern_analysis: Optional[str]
    indicator_analysis: Optional[str]
    technical_strategy: Optional[str]
    
    # Final synthesized outputs
    risk_assessment: Optional[str]
    final_report: Optional[str]